/*
 * lv_font_tm_sans.h — the content font: DejaVu Sans, 11px, 1-bit (no anti-alias,
 * so crisp on the mono OLED). Proportional → narrower than the built-in UNSCII_8,
 * with lowercase. Generated by lv_font_conv from DejaVuSans.ttf (Bitstream Vera /
 * DejaVu license — freely redistributable). line_height = TM_SANS_LINE_H.
 *
 * Used as the default content font (ui_text); the hint bar keeps lv_font_tm5x7,
 * which is thin enough for the 21px boxes.
 */
#pragma once

#include "lvgl.h"

LV_FONT_DECLARE(lv_font_tm_sans);

#define TM_SANS_LINE_H 12   /* the font's natural line height (px) */
