#!/usr/bin/env python3
"""compose_apps.py — generate main/idf_component.yml from the user-owned apps.yaml.

`apps.yaml` is THE app list (the only file you edit to add/remove apps). This script
translates it into `main/idf_component.yml`, which the ESP-IDF component manager reads.
A hook in the root CMakeLists runs it before the manager, so the generated file is a
build artifact you never hand-edit; CI can also call it directly (PLAN §6E step 1).

Deliberately dependency-free (no PyYAML): apps.yaml uses a tiny fixed subset — a list
under `apps:` of items with `name` + (`path` | `git` [+ `path`]).
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "apps.yaml")
OUT = os.path.join(ROOT, "main", "idf_component.yml")

HEADER = (
    "# ═══════════════════════════════════════════════════════════════════════════\n"
    "#  GENERATED by tools/compose_apps.py from apps.yaml — DO NOT EDIT.\n"
    "#  Edit apps.yaml (the app list); this file is regenerated on every build.\n"
    "# ═══════════════════════════════════════════════════════════════════════════\n"
)


def parse_apps(text):
    """Parse the `apps:` list. Returns a list of dicts. Minimal YAML subset."""
    apps = []
    cur = None
    in_apps = False
    for raw in text.splitlines():
        line = raw.split("#", 1)[0].rstrip()          # drop comments
        if not line.strip():
            continue
        if not line.startswith((" ", "\t")) and line.strip() == "apps:":
            in_apps = True
            continue
        if not in_apps:
            continue
        stripped = line.strip()
        if stripped.startswith("- "):                 # new list item
            cur = {}
            apps.append(cur)
            stripped = stripped[2:].strip()           # first key sits on the dash line
        if cur is None or ":" not in stripped:
            continue
        key, val = stripped.split(":", 1)
        cur[key.strip()] = val.strip()
    return apps


def render(apps):
    if not apps:
        # An empty `dependencies:` is invalid YAML; `{}` means "no user apps".
        return HEADER + "dependencies: {}\n"
    lines = [HEADER, "dependencies:\n"]
    for a in apps:
        name = a.get("name")
        if not name:
            sys.exit("compose_apps: every app needs a 'name' (got %r)" % a)
        lines.append("  %s:\n" % name)
        if "git" in a:
            lines.append("    git: %s\n" % a["git"])
            if a.get("path"):
                lines.append("    path: %s\n" % a["path"])   # subdir inside the repo
            # Optional git ref — a branch, tag, or commit (component-manager `version`).
            ref = a.get("version") or a.get("branch") or a.get("tag") or a.get("ref")
            if ref:
                lines.append("    version: %s\n" % ref)
        elif a.get("path"):
            # In-tree path is relative to the repo root; main/ needs it relative to main/.
            lines.append("    path: ../%s\n" % a["path"].lstrip("/"))
        else:
            sys.exit("compose_apps: app '%s' needs a 'path' or 'git'" % name)
    return "".join(lines)


def main():
    if not os.path.exists(SRC):
        sys.exit("compose_apps: %s not found" % SRC)
    with open(SRC, encoding="utf-8") as f:
        apps = parse_apps(f.read())
    out = render(apps)

    old = ""
    if os.path.exists(OUT):
        with open(OUT, encoding="utf-8") as f:
            old = f.read()
    if out != old:                                    # only rewrite on change (no churn)
        with open(OUT, "w", encoding="utf-8") as f:
            f.write(out)
        print("compose_apps: wrote main/idf_component.yml (%d app(s))" % len(apps))
    else:
        print("compose_apps: main/idf_component.yml up to date (%d app(s))" % len(apps))


if __name__ == "__main__":
    main()
