#!/usr/bin/env python3
"""compose_apps.py — generate main/idf_component.yml from the user-owned apps.yaml.

`apps.yaml` is THE app list (the only file you edit to add/remove apps). This script
translates it into `main/idf_component.yml`, which the ESP-IDF component manager reads.
A hook in the root CMakeLists runs it before the manager, so the generated file is a
build artifact you never hand-edit; CI can also call it directly (PLAN §6E step 1).

Deliberately dependency-free (no PyYAML): apps.yaml uses a tiny fixed subset — an
optional `core:` block (the sealed OS, git-pinned) and a list under `apps:` of items
with `name` + (`path` | `git` [+ `path`] [+ `version`/`branch`/`tag`]).
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "apps.yaml")
OUT = os.path.join(ROOT, "main", "idf_component.yml")

HEADER = (
    "# ═══════════════════════════════════════════════════════════════════════════\n"
    "#  GENERATED by tools/compose_apps.py from apps.yaml — DO NOT EDIT.\n"
    "#  Edit apps.yaml (the app list); this file is regenerated on every build.\n"
    "# ═══════════════════════════════════════════════════════════════════════════\n"
)


def parse(text):
    """Parse apps.yaml → (core dict, apps list). Minimal fixed YAML subset."""
    core = {}
    apps = []
    section = None      # 'core' | 'apps' | None
    cur = None          # the dict currently being filled
    for raw in text.splitlines():
        line = raw.split("#", 1)[0].rstrip()          # drop comments
        if not line.strip():
            continue
        if not line.startswith((" ", "\t")):          # a top-level key
            key = line.strip().rstrip(":")
            section = key if key in ("core", "apps") else None
            cur = core if key == "core" else None
            continue
        if section is None:
            continue
        stripped = line.strip()
        if section == "apps" and stripped.startswith("- "):
            cur = {}
            apps.append(cur)
            stripped = stripped[2:].strip()           # first key sits on the dash line
        if cur is None or ":" not in stripped:
            continue
        k, v = stripped.split(":", 1)
        cur[k.strip()] = v.strip()
    return core, apps


def emit_dep(name, spec):
    """One `name: {...}` dependency block for the manager (git or local path)."""
    out = ["  %s:\n" % name]
    if "git" in spec:
        out.append("    git: %s\n" % spec["git"])
        if spec.get("path"):
            out.append("    path: %s\n" % spec["path"])     # subdir inside the repo
        ref = spec.get("version") or spec.get("branch") or spec.get("tag") or spec.get("ref")
        if ref:
            out.append("    version: %s\n" % ref)           # branch / tag / commit
    elif spec.get("path"):
        # A local path is relative to the repo root; main/ needs it relative to main/.
        out.append("    path: ../%s\n" % spec["path"].lstrip("/"))
    else:
        sys.exit("compose_apps: '%s' needs a 'path' or 'git'" % name)
    return out


def render(core, apps):
    if not core and not apps:
        # An empty `dependencies:` is invalid YAML; `{}` means "no deps".
        return HEADER + "dependencies: {}\n"
    lines = [HEADER, "dependencies:\n"]
    if core:                                            # the sealed OS (template builds)
        lines += emit_dep("taskmaster_core", core)
    for a in apps:
        name = a.get("name")
        if not name:
            sys.exit("compose_apps: every app needs a 'name' (got %r)" % a)
        lines += emit_dep(name, a)
    return "".join(lines)


def main():
    if not os.path.exists(SRC):
        sys.exit("compose_apps: %s not found" % SRC)
    with open(SRC, encoding="utf-8") as f:
        core, apps = parse(f.read())
    out = render(core, apps)

    old = ""
    if os.path.exists(OUT):
        with open(OUT, encoding="utf-8") as f:
            old = f.read()
    if out != old:                                    # only rewrite on change (no churn)
        with open(OUT, "w", encoding="utf-8") as f:
            f.write(out)
        print("compose_apps: wrote main/idf_component.yml (%d app(s))" % len(apps))
    else:
        print("compose_apps: main/idf_component.yml up to date (%d app(s))" % len(apps))


if __name__ == "__main__":
    main()
